HappyBirthdayMyFriend.Web.Mvc/Models/AccountViewModels.cs
using System.ComponentModel.DataAnnotations;

namespace HappyBirthdayMyFriend.Web.Mvc.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }

    public class ManageUserViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

HappyBirthdayMyFriend.Web.Mvc/Models/IdentityModels.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace HappyBirthdayMyFriend.Web.Mvc.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection")
        {
        }
    }
}

HappyBirthdayMyFriend.Web.Mvc/Controllers/BaseController.cs
using System;
using System.Web.Mvc;
using HappyBdayMyFriend.DataAccess.Contracts;

namespace HappyBirthdayMyFriend.Web.Mvc.Controllers
{
    public class BaseController : Controller
    {
        protected IUnitOfWork UnitOfWork { get; set; }
        public int GetSecondsRemain()
        {
            var bd = new DateTime(2013, 12, 31, 6, 35, 0, DateTimeKind.Utc);
            var now = DateTime.UtcNow;
            return (int)(bd - now).TotalSeconds;
        }
	}
}

HappyBirthdayMyFriend.Web.Mvc/Controllers/GreetingsController.cs
using System.Linq;
using System.Web.Mvc;
using HappyBdayMyFriend.DataAccess.Contracts;
using HappyBdayMyFriend.Model;
using PagedList;

namespace HappyBirthdayMyFriend.Web.Mvc.Controllers
{
    public class GreetingsController : BaseController
    {
        private const int PageSize = 9;
        public GreetingsController(IUnitOfWork unitOfWork)
        {
            UnitOfWork = unitOfWork;
        }

        public ActionResult Show(int? page)
        {
            var seconds = GetSecondsRemain();
            if (seconds > 0)
            {
                return this.RedirectToAction("Index", "Home");
            }

            return ShowCards(page);
        }

        public ActionResult MyDearLordPleaseShowMeTheCards(int? page)
        {
            return ShowCards(page);
        }
         
        [NonAction]
        private ActionResult ShowCards(int? page)
        {
            int pageNumber = (page ?? 1);
            return View("Show", UnitOfWork.Cards.GetAll().OrderBy(c => c.Id).ToPagedList(pageNumber, PageSize));
        }

        public ActionResult AddPlease()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult AddPlease(Card card)
        {
            var nextCover = UnitOfWork.Cards.GetAll().Any() ? UnitOfWork.Cards.GetAll().Max(c => c.Cover) + 1 : 1;
            card.Cover = nextCover;
            UnitOfWork.Cards.Add(card);
            UnitOfWork.Commit();
            return View();
        }

        public ActionResult EditMeCarefully(int id)
        {
            var card = UnitOfWork.Cards.GetAll().FirstOrDefault(c => c.Cover == id);
            return View("AddPlease", card);
        }

        [HttpPost]
        public ActionResult EditMeCarefully(Card card)
        {
            var existingCard = UnitOfWork.Cards.GetById(card.Id);
            existingCard.Message = card.Message;
            existingCard.Signature = card.Signature;
            UnitOfWork.Cards.Update(existingCard);
            UnitOfWork.Commit();
            return RedirectToAction("Show");
        }

        public void ClearAll()
        {
            var cards = UnitOfWork.Cards.GetAll().ToArray();
            foreach (var c in cards)
            {
                UnitOfWork.Cards.Delete(c);
            }
            UnitOfWork.Commit();
        }
	}
}

HappyBirthdayMyFriend.Web.Mvc/Controllers/HomeController.cs
using HappyBdayMyFriend.DataAccess.Contracts;
using System.Linq;
using System.Web.Mvc;

namespace HappyBirthdayMyFriend.Web.Mvc.Controllers
{
    public class HomeController : BaseController
    {
        public HomeController(IUnitOfWork unitOfWork)
        {
            UnitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            var seconds = GetSecondsRemain();
            var model = seconds > 0 ? seconds : 3;
            return View(model);
        }
    }
}

HappyBirthdayMyFriend.Web.Mvc/Views/Greetings/AddPlease.cshtml
@model HappyBdayMyFriend.Model.Card
<!-- Primary Page Layout
================================================== -->
<!-- globalWrapper -->
<div id="globalWrapper" class="localscroll">
    <!-- content -->

    <section class="slice" id="contactSlice">
        <div class="container">
            <div class="row">

                <div class="col-sm-12">
                    <h1 class="noSubtitle">Создай свою открытку</h1>
                </div>

                <div class="col-sm-4">
                    <div>
                        <label>Выбери обложку</label>
                    </div>
                    <div class="cover">
                        <img src="~/Static/images/cards/card-001.jpg" />
                    </div>
                </div>
                <form method="post" role="form">
                    @Html.HiddenFor(m => m.Id)
                    @Html.HiddenFor(m => m.Cover)
                    <div class="col-sm-4">
                        <div>
                            <label>Внутренняя сторона</label>
                        </div>
                        <div class="cardOpened">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(m => m.Signature, "Подпишись")
                            @Html.TextBoxFor(m => m.Signature, new
                            {
                                @class = "form-control",
                                placeholder = "Твое имя",
                                title = "Не вредничай, подпишись"
                            })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Message, "Поздравление")
                            @Html.TextAreaFor(m => m.Message, 12, 3, new
                            {
                                @class = "form-control",
                                placeholder = "Текст поздравления…",
                                title = "Введи поздравление. Как же без него."
                            })
                        </div>
                        <div class="cardMake">
                            <button name="submit" type="submit" class="btn btn-lg" id="submit"> Submit</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </section>

    <!-- content -->
</div>
<!-- global wrapper -->
<!-- End Document
================================================== -->

HappyBirthdayMyFriend.Web.Mvc/Views/Greetings/Show.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<HappyBdayMyFriend.Model.Card>
<!-- Primary Page Layout
================================================== -->
<!-- globalWrapper -->
<div id="globalWrapper" class="localscroll">
    <!-- content -->

    <section class="slice" id="cards">

        <div class="container clearfix">
            <div class="row">
                <div class="col-sm-12">
                    <h1>А вот и твои открытки</h1>
                    <h2 class="subTitle">Прими самые искренние пожелания</h2>
                </div>
                <div class="clearfix">

                    @foreach (var card in Model)
                    {
                        <div class="col-sm-4 isotopeItem">
                            <div class="cardContainer">
                                <div class="card shadow">
                                    <div class="front face">
                                        <img src="~/Static/images/cards/card-@(card.Cover.ToString("D3")).jpg" />
                                    </div>
                                    <div class="back face">
                                        <p>@Html.Raw(card.Message)</p>
                                        <p>
                                            <strong>@card.Signature</strong>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>

                <nav id="filter" class="col-md-12 text-center">
                    @Html.PagedListPager(Model,
                        page => Url.Action(ViewContext.RouteData.GetRequiredString("action"), new { page }),
                        new PagedListRenderOptions
                                         {
                                             DisplayLinkToNextPage = PagedListDisplayMode.Never,
                                             DisplayLinkToPreviousPage = PagedListDisplayMode.Never,
                                             MaximumPageNumbersToDisplay = 30
                                         })
                </nav>
            </div>
        </div>
    </section>



    <!-- content -->
</div>
<!-- global wrapper -->
<!-- End Document
================================================== -->

HappyBirthdayMyFriend.Web.Mvc/Views/Greetings/View.cshtml
<!-- Primary Page Layout
================================================== -->
<!-- globalWrapper -->
<div id="globalWrapper" class="localscroll">
    <!-- content -->

    <section class="slice" id="contactSlice">
        <div class="container">
            <div class="row">

                <div class="col-sm-12">
                    <h1 class="noSubtitle">Создай свою открытку</h1>
                </div>

                <div class="col-sm-4">
                    <div>
                        <label>Выбери обложку</label>
                    </div>
                    <div class="cover">
                        <img src="~/Static/images/cards/card-001.jpg" />
                    </div>
                </div>
                <form method="post" role="form">

                    <div class="col-sm-4">
                        <div>
                            <label>Внутренняя сторона</label>
                        </div>
                        <div class="cardOpened">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="signature">Подпишись</label>
                            <input class="form-control" name="signature" id="signature" placeholder="Твое имя" title="Не вредничай, подпишись" />
                        </div>
                        <div class="form-group">
                            <label for="comments">Поздравление</label>
                            <textarea name="comment" class="form-control" id="comments" cols="3" rows="12" placeholder="Текст поздравления…" title="Введи поздравление. Как же без него."></textarea>
                        </div>
                        <div class="cardMake">
                            <button name="submit" type="submit" class="btn btn-lg" id="submit"> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>

    <!-- content -->
</div>
<!-- global wrapper -->
<!-- End Document
================================================== -->

HappyBirthdayMyFriend.Web.Mvc/Views/Home/Index.cshtml
@model int
@section scripts{
<script type="text/javascript" src="~/JS/ViewModels/HomePageViewModel.js"></script>
    <script type="text/javascript" src="~/JS/Bindings/Timer.js"></script>
}

<!-- Primary Page Layout
================================================== -->
<!-- globalWrapper -->
<div id="globalWrapper" class="localscroll">
    <!-- content -->
    <section id="homeFullScreen" data-stellar-background-ratio="0.5">
        <div class="maskParent">
            <div class="paralaxMask"></div>
            <div id="fullScreenSliderWrapper">
                <div id="countdown">
                    <h1 data-bind="timer: { seconds: @Model, ready: flag }"></h1>
                </div>
                <a href="@Url.Action("Show", "Greetings")" data-bind="visible: flag" class="homeBtn btn"><i class="icon-down"></i>Хочу поздравлений</a>
            </div>
        </div>
    </section>
</div>
<!-- global wrapper -->
<!-- End Document
================================================== -->

HappyBirthdayMyFriend.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->

<head>
    <!-- Basic Page Needs
    ================================================== -->
    <meta charset="utf-8">
    <title>HBNG</title>
    <meta name="description" content="HBNG">
    <!-- Mobile Specific Metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- CSS
    ================================================== -->
    <!-- Bootstrap  -->
    <link type="text/css" rel="stylesheet" href="~/Content/bootstrap.css">
    <link type="text/css" rel="stylesheet" href="~/Content/PagedList.css">
    <!-- web font  -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,800" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Exo+2&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <!-- plugin css  -->
    <link rel="stylesheet" type="text/css" href="~/Scripts/js-plugin/animation-framework/animate.css" />
    <link rel="stylesheet" type="text/css" href="~/Scripts/js-plugin/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" type="text/css" href="~/Scripts/js-plugin/flexslider/flexslider.css" />
    <link rel="stylesheet" type="text/css" href="~/Scripts/js-plugin/pageSlide/jquery.pageslide.css" />
    <!-- Owl carousel-->
    <link rel="stylesheet" href="~/Scripts/js-plugin/owl.carousel/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="~/Scripts/js-plugin/owl.carousel/owl-carousel/owl.theme.css">
    <!-- icon fonts -->
    <link type="text/css" rel="stylesheet" href="~/Static/font-icons/custom-icons/css/custom-icons.css">
    <link type="text/css" rel="stylesheet" href="~/Static/font-icons/custom-icons/css/custom-icons-ie7.css">
    <!-- Custom css -->
    <link type="text/css" rel="stylesheet" href="~/Static/css/layout.css">
    <link type="text/css" id="colors" rel="stylesheet" href="~/Static/css/sea-green.css">
    <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
    <script src="~/Scripts/js/modernizr-2.6.1.min.js"></script>

    <script type="text/javascript" src="~/Scripts/js-plugin/respond/respond.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="~/Scripts/knockout-3.0.0.js"></script>
    <!-- third party plugins  -->
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    <script type="text/javascript" src="~/Scripts/js-plugin/easing/jquery.easing.1.3.js"></script>

    <script type="text/javascript" src="~/Scripts/js-plugin/flexslider/jquery.flexslider-min.js"></script>

    <script type="text/javascript" src="~/Scripts/js-plugin/neko-contact-ajax-plugin/js/jquery.form.js"></script>
    <script type="text/javascript" src="~/Scripts/js-plugin/neko-contact-ajax-plugin/js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/Scripts/js-plugin/magnific-popup/jquery.magnific-popup.min.js"></script>
    <script type="text/javascript" src="~/Scripts/js-plugin/parallax/js/jquery.scrollTo-1.4.3.1-min.js"></script>
    <script type="text/javascript" src="~/Scripts/js-plugin/parallax/js/jquery.localscroll-1.2.7-min.js"></script>
    <script type="text/javascript" src="~/Scripts/js-plugin/parallax/js/jquery.stellar.min.js"></script>
    <!-- <script type="text/javascript" src="js-plugin/smoothscroll/SmoothScroll.js"></script> -->
    <script type="text/javascript" src="~/Scripts/js-plugin/pageSlide/jquery.pageslide-custom.js"></script>
    <script type="text/javascript" src="~/Scripts/js-plugin/jquery.sharrre-1.3.4/jquery.sharrre-1.3.4.min.js"></script>

    <script type="text/javascript" src="~/Scripts/js-plugin/owl.carousel/owl-carousel/owl.carousel.min.js"></script>


    <!-- Custom  -->
    <script type="text/javascript" src="~/Scripts/js/custom.js"></script>
    @RenderSection("scripts", false)

    <!-- Favicons
    ================================================== -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/Static/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/Static/images/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/Static/images/apple-touch-icon-144x144.png">
</head>
<body data-spy="scroll" data-target="#scrollTarget" data-offset="150" id="fullScreen">
    <!-- Preloader -->
    <div id="preloader">
        <div id="status">
            <img src="~/Static/images/theme-pics/loader.gif" alt="" /><h1 class="noSubtitle">Buon Compleanno!</h1>
        </div>
    </div>
    <!-- Preloader -->
    @RenderBody()
</body>
</html>